[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = @fghanDish
db_host = db
db_port = 5432
db_user = odoo
db_password = @fghanDish
proxy_mode = True
logfile = False
log_level = info